services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      WEBHOOK_URL: ${WEBHOOK_URL}
      WEBHOOK_PATH: ${WEBHOOK_PATH:-/telegram}
      WEBHOOK_SECRET: ${WEBHOOK_SECRET}
      DROP_PENDING: ${DROP_PENDING:-false}
      HOST: 0.0.0.0
      PORT: 8000
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "8000:8000"
    #command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    
volumes:
  db_data: